#! /bin/sh

killall -q polybar
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
polybar -q main &
polybar -q second &
killall -q sxhkd
while pgrep -u $UID -x sxhkd >/dev/null; do sleep 1; done
sxhkd &

bspc monitor DP-0 -d Firefox Chat
bspc monitor DP-2 -d Servers Vim Steam

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a firefix desktop='^1'

feh --bg-scale /home/charlie/Pictures/mountain.jpg
